on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install packages
      run: yarn --frozen-lockfile

    - name: Check linting
      run: yarn lint:check

    - name: Check formatting
      run: yarn format:check

    - name: Tests
      run: yarn test
